# -*- coding: utf-8 -*-
"""problem_6c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dMXyDglof8MUeajQK96eEOPvmkEStPy
"""

# Q6c
import numpy as np

x=[0 for i in range(16)]

for k in range(6, 16):
  a=[[1, 1], [10**(-k), 0], [0, 10**(-k)]]
  b=[[-10**(-k)], [1+10**(-k)],[1-10**(-k)]]
  at=[[a[j][i] for j in range(len(a))] for i in range(len(a[0]))]
  ata=np.matmul(at, a)
  atb=np.matmul(at, b)
  print("for k=", k)
  x[k]= np.linalg.solve(ata, atb)
  print(x[k])
  print()