# -*- coding: utf-8 -*-
"""problem_6b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19KQqbwGaRDsRAm_VOtttwRciyGHyerlH
"""

#Q6b
import numpy as np
from scipy.linalg import solve_triangular

x=[0 for i in range(16)]

for k in range(6, 16):
  a=[[1, 1], [10**(-k), 0], [0, 10**(-k)]]
  b=[[-10**(-k)], [1+10**(-k)],[1-10**(-k)]]
  q, r =  np.linalg.qr(a)
  y=np.matmul(np.transpose(q), b)
  x[k]=solve_triangular(r, y)

for i in range(6, len(x)):
  print("for k=", i)
  print(x[i])
  print()