# -*- coding: utf-8 -*-
"""problme_3a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHFUNnyuiiWrpSnqJgYNNjaT-qRDMZ4O
"""

import matplotlib.pyplot as plt
import numpy as np

def f(t):
  return 1/(1 + 25 *( t**2))

#polynomial interpolation
x=np.linspace(-1, 1, 100)
y_original=[f(t_) for t_ in x]

def polynomial(n):
  x_inter=np.linspace(-1, 1, n)
  y_inter=[]
  for x_buff in x_inter:
    y1=0
    for xi, yi in zip(x, y_original):
      y1+= yi*(np.prod((x_buff-x[x!=xi])/(xi-x[x!=xi])))
    y_inter.append(y1)

  return (x_inter, y_inter)

x11, y11=polynomial(31)
x21, y21=polynomial(51)

# plt.plot(x11, y11, 'b-')
plt.plot(x, y_original, 'b-')
plt.plot(x11, y11, 'ro')
plt.grid(True)
plt.xlim(-1.5, 1.5)
plt.ylim(-1.5, 1.5)
plt.xlabel('x')
plt.ylabel('y')
plt.show()

# plt.plot(x21, y21, 'b-')
plt.plot(x, y_original, 'b-')
plt.plot(x21, y21, 'ro')
plt.grid(True)
plt.xlim(-1.5, 1.5)
plt.ylim(-1.5, 1.5)
plt.xlabel('x')
plt.ylabel('y')
plt.show()